# Generated by Django 4.1 on 2023-05-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Char',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Character')),
                ('description', models.TextField(verbose_name='Description')),
                ('mains', models.CharField(max_length=15, verbose_name='Mains')),
                ('videos', models.CharField(max_length=256, verbose_name='Urls')),
                ('image', models.CharField(max_length=20)),
            ],
        ),
    ]
