# Generated by Django 4.1 on 2023-05-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterselect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='char',
            old_name='videos',
            new_name='video',
        ),
        migrations.AlterField(
            model_name='char',
            name='image',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='char',
            name='mains',
            field=models.TextField(verbose_name='Mains'),
        ),
    ]
