# Generated by Django 4.1 on 2023-06-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterselect', '0002_rename_videos_char_video_alter_char_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='char',
            name='video',
        ),
        migrations.AddField(
            model_name='char',
            name='pref',
            field=models.TextField(default=0, verbose_name='Preferences'),
            preserve_default=False,
        ),
    ]
