# Generated by Django 4.1 on 2023-06-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterselect', '0003_remove_char_video_char_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='char',
            name='stripname',
            field=models.CharField(default=0, max_length=15, verbose_name='stripname'),
            preserve_default=False,
        ),
    ]
