# Generated by Django 4.1 on 2023-03-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tricks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trick',
            name='filmer',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trick',
            name='insta',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
