# Generated by Django 4.1 on 2023-03-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tricks', '0002_trick_filmer_alter_trick_insta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trick',
            name='insta',
            field=models.CharField(blank=True, default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trick',
            name='ns',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
