# Generated by Django 4.1 on 2023-03-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tricks', '0003_alter_trick_insta_alter_trick_ns'),
    ]

    operations = [
        migrations.AddField(
            model_name='trick',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Beginner', 'BEGINNER'), ('Intermediate', 'INTERMEDIATE'), ('Advanced', 'ADVANCED'), ('Pro', 'PRO')], max_length=12),
        ),
        migrations.AlterField(
            model_name='trick',
            name='filmer',
            field=models.CharField(max_length=30, verbose_name='Filmer'),
        ),
        migrations.AlterField(
            model_name='trick',
            name='insta',
            field=models.CharField(blank=True, max_length=30, verbose_name='Instagram Handle'),
        ),
        migrations.AlterField(
            model_name='trick',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Trick Name'),
        ),
        migrations.AlterField(
            model_name='trick',
            name='ns',
            field=models.CharField(blank=True, max_length=30, verbose_name='Newschoolers Username'),
        ),
        migrations.AlterField(
            model_name='trick',
            name='skier',
            field=models.CharField(max_length=30, verbose_name='Skier'),
        ),
        migrations.AlterField(
            model_name='trick',
            name='video',
            field=models.CharField(max_length=255, unique=True, verbose_name='Youtube URL'),
        ),
    ]
