# Generated by Django 4.1 on 2023-03-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tricks', '0004_trick_difficulty_alter_trick_filmer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trick',
            name='email',
            field=models.CharField(default=0, max_length=40, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trick',
            name='filmer',
            field=models.CharField(max_length=30, verbose_name='filmer'),
        ),
        migrations.AlterField(
            model_name='trick',
            name='insta',
            field=models.CharField(blank=True, max_length=30, verbose_name='instagram handle'),
        ),
        migrations.AlterField(
            model_name='trick',
            name='name',
            field=models.CharField(max_length=30, verbose_name='trick Name'),
        ),
        migrations.AlterField(
            model_name='trick',
            name='ns',
            field=models.CharField(blank=True, max_length=30, verbose_name='newschoolers username'),
        ),
        migrations.AlterField(
            model_name='trick',
            name='skier',
            field=models.CharField(max_length=30, verbose_name='skier'),
        ),
        migrations.AlterField(
            model_name='trick',
            name='video',
            field=models.CharField(max_length=255, unique=True, verbose_name='youtube url'),
        ),
    ]
