# Generated by Django 4.1 on 2023-03-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tricks', '0005_trick_email_alter_trick_filmer_alter_trick_insta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trick',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
