# Generated by Django 4.1 on 2023-03-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tricks', '0007_alter_trick_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trick',
            name='difficulty',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
