# Generated by Django 4.1 on 2023-04-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tricks', '0008_alter_trick_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trick',
            name='video',
            field=models.TextField(verbose_name='youtube embed code'),
        ),
    ]
